### PR TITLE
DOC-87: remove enduser application modules (copied to quickstart projects)

### PR DESCRIPTION
**Pull request by janvenstermans**
- update parent version

Documentation in quickstart applications, GWTRAR-32 and GWTIIRAR-23 pulls have been merged.

### CODE REVIEW

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by jandm** [comment]
+1: binding

**Comment by janvenstermans** [comment]
Vote count:
Oliver May: +1 (binding)
Jan De Moerloose: +1: binding

Jan Venstermans: +1

Vote successful

**Pull request merged**
